# QART ZCU111 PS -> AXI DMA -> AXI Clock Converter transport block design
# PRE-HARDWARE: generates an integration design; it does not program or verify a board.

set design_name qart_ps_dma_transport
create_bd_design $design_name

set ps [create_bd_cell -type ip -vlnv xilinx.com:ip:zynq_ultra_ps_e:* ps]
apply_bd_automation -rule xilinx.com:bd_rule:zynq_ultra_ps_e -config {apply_board_preset "1"} $ps

set dma [create_bd_cell -type ip -vlnv xilinx.com:ip:axi_dma:* dma]
set_property -dict [list   CONFIG.c_include_sg {0}   CONFIG.c_include_mm2s {1}   CONFIG.c_include_s2mm {0}   CONFIG.c_m_axis_mm2s_tdata_width {32} ] $dma

# QHAP runs in its own selected qhap_clk domain. Never assume PS PL_CLK0
# is phase-aligned to that domain: cross through the vendor AXIS CDC IP.
set cdc [create_bd_cell -type ip -vlnv xilinx.com:ip:axis_clock_converter:* qhap_axis_cdc]

set qhap_clk [create_bd_port -dir I -type clk qhap_clk]
set_property CONFIG.FREQ_HZ 100000000 $qhap_clk
set qhap_resetn [create_bd_port -dir I -type rst qhap_resetn]
set_property CONFIG.POLARITY ACTIVE_LOW $qhap_resetn

connect_bd_intf_net [get_bd_intf_pins $dma/M_AXIS_MM2S] [get_bd_intf_pins $cdc/S_AXIS]
set qhap_axis [make_bd_intf_pins_external [get_bd_intf_pins $cdc/M_AXIS]]
set_property name QHAP_M_AXIS $qhap_axis

# AXI DMA control and DDR-read paths are attached to the Zynq PS using
# Vivado connection automation so address/data-width details follow the selected part/preset.
apply_bd_automation -rule xilinx.com:bd_rule:axi4   -config {Master "/ps/M_AXI_HPM0_FPD" Clk "Auto"}   [get_bd_intf_pins $dma/S_AXI_LITE]
apply_bd_automation -rule xilinx.com:bd_rule:axi4   -config {Master "/dma/M_AXI_MM2S" Clk "Auto"}   [get_bd_intf_pins $ps/S_AXI_HP0_FPD]

connect_bd_net [get_bd_pins $ps/pl_clk0] [get_bd_pins $dma/m_axi_mm2s_aclk]
connect_bd_net [get_bd_pins $ps/pl_clk0] [get_bd_pins $dma/s_axi_lite_aclk]
connect_bd_net [get_bd_pins $ps/pl_clk0] [get_bd_pins $cdc/s_axis_aclk]
connect_bd_net $qhap_clk [get_bd_pins $cdc/m_axis_aclk]
connect_bd_net $qhap_resetn [get_bd_pins $cdc/m_axis_aresetn]

# s_axis_aresetn follows the PS-domain reset generated by connection automation.
# Locate the active-low peripheral reset attached to the DMA and reuse it for CDC source side.
set dma_rst [get_bd_nets -of_objects [get_bd_pins $dma/axi_resetn]]
if {[llength $dma_rst] != 0} {
  connect_bd_net [get_bd_pins $cdc/s_axis_aresetn] [get_bd_pins $dma/axi_resetn]
}

assign_bd_address
validate_bd_design
save_bd_design

puts "QART_PS_DMA_TRANSPORT_BD_PASS"


# QHAP AXI-Lite control/status bank. This IP is expected to be packaged from
# fpga/rtl/qart_axil_control.sv or instantiated in the generated HDL wrapper.
# The PS control path and DMA control path share the PS AXI master; QHAP command
# data remains on the independent AXI-Stream path above.
puts "QART_CONTROL_PLANE_REQUIRED=qart_axil_control"
puts "QART_PS_DMA_TRANSPORT_BD_PASS"
