module tb_qhap_command_chain;
 logic clk=0,aresetn=0; always #1 clk=~clk;
 logic [31:0] d; logic [3:0] keep=4'hf; logic v=0,r,last=0;
 logic fv,ff; logic [31:0] magic,seq,crc_received,p0,p1; logic [7:0] version,kind;
 logic [15:0] flags,channel,action,amplitude,duration;
 logic crc_ok,permit,fault;
 qart_axis_frame_rx rx(.aclk(clk),.aresetn(aresetn),.s_axis_tdata(d),.s_axis_tkeep(keep),
 .s_axis_tvalid(v),.s_axis_tready(r),.s_axis_tlast(last),.frame_valid(fv),.frame_fault(ff),
 .magic(magic),.seq(seq),.crc_received(crc_received),.version(version),.kind(kind),.flags(flags),
 .channel(channel),.action(action),.amplitude(amplitude),.duration(duration),.payload0(p0),.payload1(p1));
 // Golden frame below is generated by hardware/qhap_frame.py in CI.
 logic [31:0] expected_crc;
 assign crc_ok=(crc_received==expected_crc);
 qart_frame_guard gate(.valid(fv),.magic(magic),.version(version),.kind(kind),.seq(seq),
 .channel(channel),.action(action),.amplitude(amplitude),.duration(duration),.crc_ok(crc_ok),
 .expected_seq(32'd7),.permit(permit),.fault(fault));
 task beat(input [31:0] x,input bit l); begin
  @(negedge clk);d=x;v=1;last=l; @(negedge clk);v=0;last=0;
 end endtask
 initial begin
  d=0;expected_crc=32'h0;repeat(2) @(negedge clk);aresetn=1;
  $readmemh("tests/qhap_e2e_words.hex", mem);
  expected_crc=mem[7];
  beat(mem[0],0);beat(mem[1],0);beat(mem[2],0);beat(mem[3],0);
  beat(mem[4],0);beat(mem[5],0);beat(mem[6],0);beat(mem[7],1);
  // frame_valid/permit are combinationally observable during the final accepted beat.
  if(!fv||!permit||fault) $fatal(1,"valid Python QHAP command was not permitted");
  $display("QHAP_E2E_COMMAND_CHAIN_PASS");$finish;
 end
 logic [31:0] mem[0:7];
endmodule
