module tb_qhap_command_chain;
 logic clk=0,aresetn=0; always #1 clk=~clk;
 logic [31:0] d; logic [3:0] keep=4'hf; logic v=0,r,last=0;
 logic fv,ff; logic [31:0] magic,seq,crc_received,p0,p1; logic [7:0] version,kind;
 logic [15:0] flags,channel,action,amplitude,duration;
 logic crc_ok,permit,fault;
 qart_axis_frame_rx rx(.aclk(clk),.aresetn(aresetn),.s_axis_tdata(d),.s_axis_tkeep(keep),
 .s_axis_tvalid(v),.s_axis_tready(r),.s_axis_tlast(last),.frame_valid(fv),.frame_fault(ff),
 .magic(magic),.seq(seq),.crc_received(crc_received),.version(version),.kind(kind),.flags(flags),
 .channel(channel),.action(action),.amplitude(amplitude),.duration(duration),.payload0(p0),.payload1(p1));
 // Golden frame below is generated by hardware/qhap_frame.py in CI.
 logic [31:0] expected_crc;
 assign crc_ok=(crc_received==expected_crc);
 qart_frame_guard gate(.valid(fv),.magic(magic),.version(version),.kind(kind),.seq(seq),
 .channel(channel),.action(action),.amplitude(amplitude),.duration(duration),.crc_ok(crc_ok),
 .expected_seq(32'd7),.permit(permit),.fault(fault));
 task beat(input [31:0] x,input bit l); begin
  @(negedge clk);d=x;v=1;last=l; @(negedge clk);v=0;last=0;
 end endtask
 initial begin
  d=0;expected_crc=32'h0;repeat(2) @(negedge clk);aresetn=1;
  $readmemh("tests/qhap_e2e_words.hex", mem);
  expected_crc=mem[7];
  beat(mem[0],0);beat(mem[1],0);beat(mem[2],0);beat(mem[3],0);
  beat(mem[4],0);beat(mem[5],0);beat(mem[6],0);beat(mem[7],1);
  // beat() returns at the negedge immediately after the final accepting posedge.
  // Sample the one-cycle frame_valid/permit pulse before the next posedge clears it.
  #0;
  if(!fv||!permit||fault) begin
    $display("E2E fv=%0b permit=%0b fault=%0b magic=%08x ver=%0d kind=%0d seq=%0d ch=%0d act=%0d amp=%04x dur=%0d crc=%08x expcrc=%08x",
      fv,permit,fault,magic,version,kind,seq,channel,action,amplitude,duration,crc_received,expected_crc);
    $fatal(1,"valid Python QHAP command was not permitted");
  end

  // Negative-path checks at the execution gate: every invalid condition must fail closed.
  expected_crc=mem[7]^32'h00000001; #1;
  if(permit||!fault) $fatal(1,"CRC corruption was not fail-closed");
  expected_crc=mem[7]; #1;
  force seq=32'd8; #1; if(permit||!fault) $fatal(1,"sequence mismatch was not fail-closed"); release seq;
  force channel=16'd64; #1; if(permit||!fault) $fatal(1,"channel bound was not fail-closed"); release channel;
  force action=16'd3; #1; if(permit||!fault) $fatal(1,"action bound was not fail-closed"); release action;
  force amplitude=16'h8000; #1; if(permit||!fault) $fatal(1,"amplitude bound was not fail-closed"); release amplitude;
  force duration=16'd0; #1; if(permit||!fault) $fatal(1,"duration bound was not fail-closed"); release duration;
  force kind=8'd2; #1; if(permit||!fault) $fatal(1,"telemetry frame reached command path"); release kind;
  force kind=8'd3; #1; if(permit||!fault) $fatal(1,"ack frame reached command path"); release kind;
  force kind=8'd4; #1; if(permit||!fault) $fatal(1,"fault frame reached command path"); release kind;
  $display("QHAP_E2E_COMMAND_CHAIN_PASS");$finish;
 end
 logic [31:0] mem[0:7];
endmodule
